name: Compile OpenTX Firmware
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          ref: '2.3'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi python3-pillow python3-pip cmake make

      - name: Configure and Build OpenTX
        run: |
          # Переводим сборку на архитектуру ARM32 под ревизию платы STM32F4VE (8 МГц)
          cmake -B build \
            -DCMAKE_SYSTEM_NAME=Generic \
            -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
            -DCMAKE_C_COMPILER=arm-none-eabi-gcc \
            -DCMAKE_CXX_COMPILER=arm-none-eabi-g++ \
            -DPCB=ARM32 \
            -DPCBREV=STM32F4VE \
            -DDISABLE_COMPANION=YES \
            -DLCD=ILI9341 \
            -DSERVO_TESTER=NO \
            -DHELI=NO
          
          # Запускаем компиляцию прошивки
          cmake --build build -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opentx-stm32f407-firmware
          path: |
            build/*.bin
            build/*.hex
