name: Compile OpenTX Firmware
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          ref: '2.3'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi python3-pillow python3-pip cmake

      - name: Configure and Build via CMake
        run: |
          # Запускаем конфигурацию CMake без лишних скриптов тестирования
          cmake -B build \
            -DPCB=STM32F4VE \
            -DPCBREV="" \
            -DDISABLE_COMPANION=YES \
            -DLCD=ILI9341 \
            -DSERVO_TESTER=NO \
            -DHELI=NO
          
          # Запускаем саму компиляцию
          cmake --build build -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opentx-stm32f407-firmware
          path: |
            build/*.bin
            build/*.hex
