name: Compile OpenTX Firmware
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2  # Обновлено: теперь без предупреждений Node.js
        with:
          ref: '2.3'

      - name: Download Toolchain and Compile
        run: |
          # 1. Скачиваем официальный Linux-компилятор ARM GCC напрямую с серверов ARM
          curl -L -s "https://arm.com" | tar -xJ
          
          # 2. Прописываем пути к компиляторам и запускаем конфигурацию платы
          cmake -B build \
            -DCMAKE_C_COMPILER=$(pwd)/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc \
            -DCMAKE_CXX_COMPILER=$(pwd)/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++ \
            -DPCB=STM32F4VE -DPCBREV= -DDISABLE_COMPANION=YES -DLCD=ILI9341
          
          # 3. Собираем проект
          cmake --build build -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opentx-stm32f407-firmware
          path: |
            build/*.bin
            build/*.hex

